### ISSUE TITLE
Feature Request: pre-defined student input. 

### ISSUE THREAD

**Issue by alendit** [trampgeek/moodle-qtype_coderunner#10]
Hi,

we would like to be able to set a pre-defined input for a CodeRunner question which then has to be completed by the student, i.e. something like that

```
def sort(input_list):
    # your code goes here

def main():
    input_list = read_list()
    print(sort(input_list))
```

I was unable to find a way to do this. Are there any interest in this functionality? I'd take a shot at it, if you are ready to merge it.

**Comment by trampgeek** [comment]
Hi Dimitri

Many thanks for raising this issue. One or two other users have asked 
for something similar, too. I would certainly like to explore such ideas 
with you.

I should begin by mentioning that there are two ways of asking questions 
of the sort you propose with the existing system.

 1. You can write a template that inserts the student answer into the
    skeleton code (possibly with extra indentation, in the case of
    Python) and then runs that code either by calling /eval/ on it or by
    compiling and executing it, depending on the language. I've written
    quite a few questions of that form e.g. asking them to write a
    method for a given class. I can show you examples of such questions
    if you're interested.
 2. You can tell the student to copy the given skeleton code into the
    answer box and tell them to add the missing code. The template then
    simply checks if the program as a whole behaves as expected.

Both of these approaches work fine but are a bit clumsy.

Your suggestion of pre-loading the answer box with code supplied by the 
question author is appealing as an improvement on method 2 above, but I 
do have a couple of reservations. Firstly, it requires yet another form 
field in the question authoring interface, which is already a bit of a 
nightmare. I'm anxious to avoid complicating that interface much more. 
Secondly, pre-loading the answer box and then checking the behaviour of 
the program when the student submits it is open to abuse by the student 
through editing of the skeleton code. For example, if you give students 
a skeleton in which the main function uses a class that you want them to 
write, but they don't understand classes, they can modify the main to 
solve the problem some other way altogether.  While this doesn't matter 
too much in a lab context (if students are determined not to learn, 
there's not too much we can do) but is serious in tests and exams.

My ideal would be to have an answer form in which the skeleton code was 
write-locked so the students could insert code only at specified places. 
[Although even that could be slightly clumsy for students wanting to 
test their code in an IDE before submitting as they would then have to 
manually select and copy just the changed bits back into the answer 
box.]  I see there's some discussion of how the ACE editor might provide 
such functionality at 
http://stackoverflow.com/questions/24958589/ace-editor-lock-or-readonly-code-segment.

A simpler approach, which I've used on occasion with questions of type 2 
above, is to have the template pattern match the submitted code against 
the original skeleton, rejecting it if the skeleton portion has been 
changed. This is a lot of work for the question author if done on a 
per-question basis but could be built into a prototype. The biggest 
disadvantage would then be that if the student made some trivial and 
perhaps inadvertent change to the skeleton while editing their own code 
into it they would get their answer rejected and mightn't even know why 
unless a very detailed error message were generated.

What approach did you have in mind?

Putting my reservations to one side I do think this is an important need 
and I'd be delighted to have you work on it. I think, though, they we 
should have a special development branch to explore ideas with, until 
we're sure we're doing things the best way for the longer term. How does 
that sound to you?

Richard

**Comment by sam-suresh** [comment]
I have need of similar feature. 
I need my student to finish the unfinished code. 

For example in codeacademy.com. 

It will be awesome if you could provide example in your site.

**Comment by trampgeek** [comment]
Hi Sam-Suresh. Thanks for your interest. I haven't yet made significant progress on adding specific functionality for "fill-in-the-gaps" questions, so you have to use the existing functionality (i.e. customised templates or prototypes) for such questions. 

I'd like to move this discussion to the forum on coderunner.org.nz, please, so we can explore options a bit better. Would you mind re-posting there, with an example of a programming question you wish to ask? My experience of codeacademy.com is limited to trivial questions like "_Create a variable called eggs and assign it the value of False_" which is trivial in CodeRunner too.

At the other end of the scale, the Python3 demo quiz on coderunner.org.nz includes (question 8) an assignment-level exercise in which students have to fill out the bodies of various functions, which are then tested separately. I suspect you're thinking of much simpler questions than this, and I'd like to have a better idea of what sort of question you wish to ask so I can propose a solution.

Richard

**Comment by trampgeek** [comment]
Version 3.1 has the ability to preload the answerbox, so I'm going to close this issue.
Richard
