### ISSUE TITLE
jobe with https

### ISSUE THREAD

**Issue by nunoguerreiro** [trampgeek/moodle-qtype_coderunner#100]
My jobe server is running and working behind a https, but in moodle when I try to run a sample quiz (python3) gives errors:

https://xxxx.xxxx.xxx.xx/jobe/index.php/restapi/languages returns:
[["c","7.5.0"],["cpp","7.5.0"],["java","11.0.7"],["nodejs","8.10.0"],["pascal","3.0.4"],["php","7.2.24"],["python2","2.7.17"],["python3","3.6.9"]] and all is working, 

in Moodle gives a error saying that sandbox is not running or there was an error processing the python question.

Moodle 3.9 version.

**Comment by trampgeek** [comment]
What URL have you entered for the Jobe server in the CodeRunner plugin settings?

**Comment by nunoguerreiro** [comment]
https://xxxx.xxxx.xxx.xx/jobe

**Comment by nunoguerreiro** [comment]
result here: 
![image](https://user-images.githubusercontent.com/1771943/85629927-c7f64d00-b683-11ea-9de9-4518f24f5caa.png)

**Comment by nunoguerreiro** [comment]
In the logs I cannot even see any error (not sure the stdout log to check).
was in apache.log and error.log and nothing there

**Comment by trampgeek** [comment]
Drop the jobe off the end. The URL you provided is used as the base 
address: /jobe/index.php/restapi  is appended by CodeRunner. So your URL 
will result in CodeRunner trying to access 
https://xxxx.xxxx.xxx.xx/jobe/jobe/index.php/restapi

**Comment by nunoguerreiro** [comment]
If you look above, that's exactly what I did

https://xxxx.xxxx.xxx.xx   here:
![image](https://user-images.githubusercontent.com/1771943/85848798-d8f5aa00-b7ba-11ea-8ecc-5631b08663e7.png)

**Comment by trampgeek** [comment]
Is it possible the moodle server is firewalled to prevent outgoing https connections? Are you able to login to the Moodle server and try a command like wget https://xxx.xxx.xxxx/jobe/index.php/restapi/languages?

It's not clear whether you've been able to get Jobe working with an http connection in the past and the problems have only just arisen when you've switched to https.

If possible you should also make sure that the Moodle administrator debugging options are set to display all error messages. That may also result in error messages previously being suppressed now being logged in the apache error log.

**Comment by nunoguerreiro** [comment]
our server is https and all is returning as expected.

https://xxx.xxx.xxxx/jobe/index.php/restapi/languages? 

[["c","7.5.0"],["cpp","7.5.0"],["java","11.0.7"],["nodejs","8.10.0"],["pascal","3.0.4"],["php","7.2.24"],["python2","2.7.17"],["python3","3.6.9"]]

**Comment by trampgeek** [comment]
Just to clarify: is that the response when you entered that link in the browser or is it what you got as a response file by typing the command 

    wget https://xxx.xxx.xxxx/jobe/index.php/restapi/languages

as a bash command running on the Moodle server? The latter is what I'm suggesting you try, in order to see if the Moodle server is firewalled to block outgoing HTTPS connections.

Perhaps most importantly of all - why are you using https, rather than http? The latter is tried and tested and used by nearly everyone. In this context https gains you virtually nothing.

**Comment by trampgeek** [comment]
Closing as no correspondence for over one year.
