### ISSUE TITLE
It would be more friendly if php unit tests were flagged as skipped when sandbox not setup.

### ISSUE THREAD

**Issue by danmarsden** [trampgeek/moodle-qtype_coderunner#104]
Hey @trampgeek - just wondering why your test-sandbox-config-dist.php sets:

jobesandbox_enabled = 1

It might be slightly more friendly to set it to 0 by default, and then if devs want to run through all the tests they set up a test-sandbox-config.php that turns that one on?

this way - if we drop your plugin into a site running continuous integration the coderunner tests are just skipped until a sandbox is setup.

thanks!

**Comment by trampgeek** [comment]
OK, thanks for the suggestion. I've made that change in the development branch I'm currently working on, so it will appear in due course in the master.

**Comment by danmarsden** [comment]
awesome thanks!
