### ISSUE TITLE
Request: Support the two-argument random() function in Twig.

### ISSUE THREAD

**Issue by krivit** [trampgeek/moodle-qtype_coderunner#105]
The current Twig implementation (https://twig.symfony.com/doc/3.x/functions/random.html), allows the user to call `random(a,b)`, returning a random integer between `a` and `b`, inclusive. As far as I can tell, this format is not supported in CodeRunner's rewrite (and silently produces incorrect results):
https://github.com/trampgeek/moodle-qtype_coderunner/blob/00ea31458f940ad9112d742f4dd7c21ae2548ef6/classes/twig.php#L97

Would it be possible to add this capability?

**Comment by trampgeek** [comment]
I've updated the version of Twig in the latest release of CodeRunner, so hopefully this problem is solved now. Please re-open if not.
