### ISSUE TITLE
Request: Make log(), exp(), and other mathematical functions available for Twig templating.

### ISSUE THREAD

**Issue by krivit** [trampgeek/moodle-qtype_coderunner#106]
I am using randomised questions in some of my assessments, and it would be very helpful if I could use some of the standard mathematical functions in addition to the operations provided by Twig. (For example, if I had access to the `log()` function, I could generate variates from the normal distribution with the Box-Muller transform.) Or, is there a simple workaround that I am missing? Thank you in advance.

**Comment by trampgeek** [comment]
The latest version of CodeRunner now allows languages other than Twig to be used to pre-process the template parameters. So you can now use functions in any language of your choice. Be warned, however, that there could be severe performance impacts at the start of a test if there are many such questions in the test or very large numbers of students. I'll close this on the assumption that it addresses your concerns, but if not would you mind posting your requests to the question author's forum on coderunner.org.nz, please.
