### ISSUE TITLE
403 error after added quiz with python. 

### ISSUE THREAD

**Issue by matematyk** [trampgeek/moodle-qtype_coderunner#107]
I have an issue with the added question for quiz.

I have information in URL /question/question.php "Forbidden You don't have permission to access this resource." 
But it's only for option python2, python3, python3_w_input: 

For others languages it's work. 

What could it be?

**Comment by trampgeek** [comment]
That's certainly odd. I can't immediately think of a cause. Would you mind posting the question on the question author's forum at coderunner.org.nz including a screen dump showing the actual error so I can see the context, please? Also please tell me a bit about your Jobe server. And, if you're a system administrator, make sure that the error doesn't happen when using the default University of Canterbury's Jobe server (i.e. as an administrator use the plugin-settings page to switch back to that default server).

**Comment by trampgeek** [comment]
Closing as no further correspondence since November 2020.
