### ISSUE TITLE
How to set compiler to c99

### ISSUE THREAD

**Issue by sangdv** [trampgeek/moodle-qtype_coderunner#109]
Hi, could you please guide me how to set the default gcc of the Jobe sandbox to C99?

**Comment by trampgeek** [comment]
I thought the default was already C99. Can you post some evidence that it's not, please?

In general, to change the gcc otions for a CodeRunner question, you enter a JSON string like {"compileargs": ["-std=c99"]} into the sandbox parameters, which are in the Advanced Customisation section of the author's form. If you want this to apply to all questions, do this in the question prototype (preferably not the built-in prototype but one of your own, derived from it), but if it's a one-off requirement, do it by customising the particular question (click the 'Customise' checkbox to expose the extra capabilities).

I'm closing this stream as it's not really an issue with jobe. Please post further comments/queries either to the question author's forum on coderunner.org.nz.
