### ISSUE TITLE
problem with warning messages

### ISSUE THREAD

**Issue by sangdv** [trampgeek/moodle-qtype_coderunner#110]
I customized the default parameters as {"compileargs": ["-std=c++98"]} in order  to use gets() function. However, I received the following error and got zero score:
Syntax Error(s)
__tester__.cpp: In function ‘int main()’:
__tester__.cpp:4:13: warning: ‘char* gets(char*)’ is deprecated [-Wdeprecated-declarations]
     gets(str);
             ^
In file included from __tester__.cpp:1:0:
/usr/include/stdio.h:577:14: note: declared here
 extern char *gets (char *__s) __wur __attribute_deprecated__;
              ^~~~
/tmp/cc6qfdrq.o: In function `main':
__tester__.cpp:(.text+0x1f): warning: the `gets' function is dangerous and should not be used.

It seems that Coderunner treats warnings as errors. How to ignore warnings?

**Comment by trampgeek** [comment]
If you want to ignore warnings you should set the compile args to do so. But ignoring warnings regarding gets seems like bad practice to me!
