### ISSUE TITLE
New feature: go to line/column in Ace editor inside pre-loaded answer

### ISSUE THREAD

**Issue by tmuras** [trampgeek/moodle-qtype_coderunner#114]
It would be awesome if inside " Answer box preload " one could set a marker where the cursor should go when the question is opened.
For Ace editor this seems possible with gotoLine API https://ace.c9.io/#nav=api&api=editor

**Comment by trampgeek** [comment]
Sorry Tomasz but I'm not keen on this idea. It would complicate the UI, as there would need to be a defined way to set the marker. Furthermore it's more work than you might expect, as Ace is just one of a range of UI plugins and that functionality would seem to be Ace specific. I would either have to provide special-case code for the Ace plugin, or a more-general mechanism for specifying and passing UI parameters.

**Comment by tmuras** [comment]
That's understandable, thanks for considering it!

And BTW thank you for the work on the plugin so far - it's great.
