### ISSUE TITLE
Feature Request: Limit Students entries

### ISSUE THREAD

**Issue by krendlV** [trampgeek/moodle-qtype_coderunner#116]
Hi Richard, 

I`m Moodle Admin at an Austrian University and we use CR extensively. It`s a great tool. 

Moodle Version: 3.9.4+ (Build: 20210122)
CR Version: 3.7.9+ (2020101501)

We run into a problem using coderunner: If we let a CR-Quiz accessible for several days some students try to solve the questions by doing hundreds of entries. This gets problematic when we want to change the question and do a "dry run regrade" in the quiz. 
There are too many entries for the "dry run regrade" manually regrading single participants works. 
Is it possible to limit the max. entries a student can make and if not could the feature be implemented?

Thank you very much

Kind Regards
Valentin

**Comment by trampgeek** [comment]
Firstly, are you quite sure that the dry run regrade doesn't actually finish eventually (perhaps some hours later)? We often run regradings that time out in the browser but continue to run in the background.

Also, I'm wondering why students are making so many submissions? It sounds like there is no penalty regime in place to deter this. The only situation in which we get large numbers of submissions is when we have a 0 penalty regime or, sometimes, with prechecking in a complex context where students can't get equivalent results in their IDE.

There is a solution available in version 4. The template parameter {{ QUESTION.stepinfo }} now has attributes _numchecks_ and_numprechecks_   which are the counts of prior checks and prechecks. You could change your question templates to check if some limit (perhaps set in the template parameters field) has been reached, and abort the testing. For example, your template could begin

`{% if QUESTION.stepinfo.numchecks >= 3 %}`
`    raise Exception("Submission limit reached. Testing aborted.")`
`{% endif %}`

**Comment by trampgeek** [comment]
Closing as there is a workaround in version 4 and I don't know of any other way to deal with the problem. Please re-open if you have further suggestions.
