### ISSUE TITLE
unrelated question precheck can act to update other question display count

### ISSUE THREAD

**Issue by 26F** [trampgeek/moodle-qtype_coderunner#117]
Clicking precheck on an unrelated question can be used to update the display of another question. This can be used on a multi-choice question to see how many are answered correctly, by changing the answers one can obtain the correct set of answers without taking additional penalty. The question must be submitted once in order for it to display the count, but after that students can click precheck on an unrelated question for it to update the number of correct answers in the multi-choice question.

**Comment by trampgeek** [comment]
This is true, but is nothing to do with CodeRunner. It's a bug in how Adaptive Behaviour operates in Moodle. If you're using that behaviour in a quiz with no CodeRunner questions I think you'll find that you can get the same leakage of information simply by navigating away from the page then back in again. You might want to try other behaviours, instead. CodeRunner uses Adaptive mode itself but that won't affect other non-CodeRunner questions in the same quiz.

**Comment by trampgeek** [comment]
Closing as no further correspondence and it's not really a CodeRunner issue.
