### ISSUE TITLE
$_SERVER['REQUEST_URI'] validation

### ISSUE THREAD

**Issue by tmuras** [trampgeek/moodle-qtype_coderunner#119]
The content of $_SERVER['REQUEST_URI'] is used to generate HTML output directly in 
https://github.com/trampgeek/moodle-qtype_coderunner/blob/f66e0c0e5d7a7fd33b84e328b626cacf1b9f9146/autotagbycategory.php#L70 
and
https://github.com/trampgeek/moodle-qtype_coderunner/blob/f66e0c0e5d7a7fd33b84e328b626cacf1b9f9146/autotagbyquiz.php#L69

This may be used to inject any HTML. The browser will normally send the GET request encoded but you can try to do the following test with curl:

```
➜ curl http://127.0.0.1:8765/autotagbycategory.php/\>\<b\>hello\</b\>
...
<form action=/autotagbycategory.php/><b>hello</b> method=POST>
<input type='hidden' name='contextid' value='' />
...
```

I think we should validate / normalize $_SERVER['REQUEST_URI'] on the server side.

**Comment by trampgeek** [comment]
Thanks for reporting. These scripts are indeed potentially unsafe in various ways and I really didn't intend them to be part of the official distribution. They were for local use only. They've now been deleted.
