### ISSUE TITLE
Fixed database table prefixes utilised. Is it intentional?

### ISSUE THREAD

**Issue by vsotirasqmplus** [trampgeek/moodle-qtype_coderunner#132]
This file contains {tables} and mdl_tables. Is this intentional ?
https://github.com/trampgeek/moodle-qtype_coderunner/blob/master/classes/bulk_tester.php

**Comment by trampgeek** [comment]
Not intentional, no. Fixed in the current version. Will appear here on the next push.

Many thanks.
