### ISSUE TITLE
Wrong declaration in privacy.php

### ISSUE THREAD

**Issue by asbl** [trampgeek/moodle-qtype_coderunner#138]
Hello,

In privacy.php ( https://github.com/trampgeek/moodle-qtype_coderunner/blob/master/classes/privacy/provider.php ) , the declaration of the method 'get_reason()' does not match with parent class.

It should be 
'''
 public static function get_reason() : string {
'''

(Otherwise, errors are thrown when deleting contexts with the privacy api.)

**Comment by trampgeek** [comment]
THanks. Fixed in development version. Will go out on next merge to master and push.
