### ISSUE TITLE
Plugin not working on Moodle 4.0

### ISSUE THREAD

**Issue by raveiga** [trampgeek/moodle-qtype_coderunner#141]
The new version 4.0 of Moodle removed the field category on table mdl.question.

So trying to show a questionnaire with coderrunner questions shows the following error:

Unknown column 'q.category' in 'on clause'
SELECT q.id
FROM mdl_question_coderunner_options qco
JOIN mdl_question q ON qco.questionid = q.id
JOIN mdl_question_categories qc ON qc.id = q.category
WHERE qco.prototypetype != 0
AND qc.contextid IN (?,?,?)
AND qco.coderunnertype = ?
[array (
0 => '29259',
1 => '38',
2 => '1',
3 => 'java_program',
)]
Error code: dmlreadexception
×Trazado de la pila (stack):
line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 1273 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 515 of /question/type/coderunner/questiontype.php: call to mysqli_native_moodle_database->get_records_sql()
line 409 of /question/type/coderunner/questiontype.php: call to qtype_coderunner::get_prototype()
line 961 of /lib/questionlib.php: call to qtype_coderunner->get_question_options()
line 1028 of /lib/questionlib.php: call to _tidy_question()
line 182 of /mod/quiz/attemptlib.php: call to get_question_options()
line 170 of /mod/quiz/locallib.php: call to quiz->load_questions()
line 2685 of /mod/quiz/locallib.php: call to quiz_start_new_attempt()
line 113 of /mod/quiz/startattempt.php: call to quiz_prepare_and_start_new_attempt()

**Comment by DigitalRevenant** [comment]
I got excited and jumped the gun too.

Revert or disable coderunner I am afraid. The questions table has been split into three - question_versions, question_bank_entries and question. I suspect that at least running questions could be made to work by using a subquery to re-assemble the format of the original question table where it is referenced in a SELECT. Any UPDATE queries will, of course, not work this way.

The above is just an idea, has not been tested and so is entirely caveat emptor! I am in coursework marking land at the moment, but I might give it a try if the official fix takes a while.

**Comment by trampgeek** [comment]
I've started to look into it and I have the main functionality working. But Moodle 4.0 has made a lot of major changes and it will be at least several weeks before a version of CodeRunner for Moodle 4.0 is officially released through the Moodle plugin repository. There will perhaps be a beta release on github in the development branch in a week or two if you want to be a beta tester?

**Comment by blink38** [comment]
I'm interesting in being a beta tester. I am actually migrating to Moodle 4.0 and I need the code runner plugins to be running. So, if I can help.

**Comment by trampgeek** [comment]
Great! Thanks for volunteering, blink38. At least 3 people are running it, with no issues reported yet. It runs the entire test suite no problems. 

To try it out, just select the development and pull from there. I'd be grateful if you could report how things go in the [Question Author's Forum on coderunner.org.nz](https://coderunner.org.nz/mod/forum/discuss.php?d=507), where there's already a conversation going. But feedback by any channel would be welcome.
