### ISSUE TITLE
How to get the code execution time and the memory consumed by the code

### ISSUE THREAD

**Issue by lulaodi** [trampgeek/moodle-qtype_coderunner#142]
Thank you very much for providing such a great plug-in,I not only care about the results of the student code, but also want to know the execution efficiency of the code.I noticed that the maximum CPU running time and maximum execution memory parameters can be set. Is there any way for Moodle to get the code execution time and the memory consumed by the code, or does it need to modify the configuration of the jobe server? If so, what should I do? Can you give me some tips,thanks

**Comment by trampgeek** [comment]
You can get the execution time by writing your own question type that runs the code with the linux *time* command, e.g. time ./prog. The documentation section [Supporting or Implementing New Languages](https://github.com/trampgeek/moodle-qtype_coderunner#supporting-or-implementing-new-languages) shows how to manage the execution of a program on the Jobe server using the Python subprocess module. You could replace the line "output = subprocess.check_output(["./prog"], universal_newlines=True)" with a call to subprocess.run, catching the stdout and stderr output in separate variables. [I'm assuming the output from time comes out in stderr, though I'm not sure about that.] Then you could do whatever you wanted with the time output.

I'm not sure there's a way to find how much memory was used - it's a very ill-defined concept, as different languages allocate memory in different ways and in different sized chunks. You're on your own there, I'm afraid.

This question really belong in the question author forum on coderunner.org.nz - please post any further questions there.
