### ISSUE TITLE
it doesn't show in activities list anymore...

### ISSUE THREAD

**Issue by vincentvije** [trampgeek/moodle-qtype_coderunner#146]
Hello there,
Moodle allow to install coderunner as compatible with Moodle 4.0.
I installed it, but it doesn't show in activities list...
Do you plan to repair this issue, please ?
I downloaded from github page, but it's the same, it doesn't show in activities list...
Thanks in advance, regards.
Vincent

**Comment by vincentvije** [comment]
Hello there

Yesterday, I couldn't found the question type "coderunner" in the quiz questions list.
Furthermore when I wanted to open old quizzes with conderunner, I got always a DB error from moodle.
I tried to install from github, but the same two problems.  Restarting the server didn't solved the problem. The DB was clean.
This morning, I replaced all the files directly with the github download zip, and now it works.
Maybe some issue with the moodle upgrade from 3.9 to 4.0 ?
Anyway I wrote all this in the case it could help some other persons.

Another issue is that there is no "uninstall" button for coderunner in the moodle plugin list. I don't know why.

It's then all working well now.

Regards,
Vincent

**Comment by trampgeek** [comment]
The CodeRunner release for Moodle 4 is a release candidate only. Perhaps when upgrading Moodle, the system will only install Stable versions? There should have been a warning, though.

For uninstall instructions, see here: https://github.com/trampgeek/moodle-qtype_coderunner#uninstalling-coderunner
