### ISSUE TITLE
ERROR: column mdl_question.category does not exist

### ISSUE THREAD

**Issue by dluschan** [trampgeek/moodle-qtype_coderunner#150]
Hello.
I get an error whenever I interact with CodeRunner questions.

Your Moodle code is up-to-date!
Check for available updates
Last check done on 28 September 2022, 3:33 PM
Moodle 4.0.4+ (Build: 20220922) Version 2022041904.02 (Stable version)

Plugins version: Last check done on 28 September 2022, 3:36 PM
CodeRunner qtype_coderunner 4.2.3 2022022300
Adaptive adapted for coderunner qbehaviour_adaptive_adapted_for_coderunner 1.4.1 2021112300

Debug info: ERROR: column q.category does not exist
LINE 5: ... JOIN mdl_question_categories qc ON qc.id = q.category
^

SELECT qco.*
FROM mdl_question_coderunner_options qco
JOIN mdl_question q ON q.id = qco.questionid
JOIN mdl_question_categories qc ON qc.id = q.category
WHERE prototypetype != 0 AND qc.contextid IN ($1,$2,$3,$4)
-- line 479 of /question/type/coderunner/questiontype.php: call to pgsql_native_moodle_database->get_records_sql()
-- line 1265 of /question/type/coderunner/edit_coderunner_form.php: call to qtype_coderunner::get_all_prototypes()
-- line 477 of /question/type/coderunner/edit_coderunner_form.php: call to qtype_coderunner_edit_form->get_languages_and_types()
-- line 65 of /question/type/coderunner/edit_coderunner_form.php: call to qtype_coderunner_edit_form->make_questiontype_panel()
-- line 214 of /lib/formslib.php: call to qtype_coderunner_edit_form->definition()
-- line 128 of /question/type/edit_question_form.php: call to moodleform->__construct()
-- line 218 of /question/type/questiontypebase.php: call to question_edit_form->__construct()
-- line 203 of /question/bank/editquestion/question.php: call to question_type->create_editing_form()
[array (
0 => '36',
1 => '26',
2 => '1499',
3 => '1',
)]
Error code: dmlreadexception

Stack trace:
line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 291 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 338 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->read_slave_query_end()
line 1017 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 479 of /question/type/coderunner/questiontype.php: call to pgsql_native_moodle_database->get_records_sql()
line 1265 of /question/type/coderunner/edit_coderunner_form.php: call to qtype_coderunner::get_all_prototypes()
line 477 of /question/type/coderunner/edit_coderunner_form.php: call to qtype_coderunner_edit_form->get_languages_and_types()
line 65 of /question/type/coderunner/edit_coderunner_form.php: call to qtype_coderunner_edit_form->make_questiontype_panel()
line 214 of /lib/formslib.php: call to qtype_coderunner_edit_form->definition()
line 128 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 218 of /question/type/questiontypebase.php: call to question_edit_form->__construct()
line 203 of /question/bank/editquestion/question.php: call to question_type->create_editing_form()

moodle=> SELECT table_schema, table_name, column_name, data_type 
moodle-> FROM INFORMATION_SCHEMA.COLUMNS 
moodle-> WHERE table_name = 'mdl_question';
 table_schema |  table_name  |      column_name      |     data_type     
--------------+--------------+-----------------------+-------------------
 public       | mdl_question | id                    | bigint
 public       | mdl_question | parent                | bigint
 public       | mdl_question | name                  | character varying
 public       | mdl_question | questiontext          | text
 public       | mdl_question | questiontextformat    | smallint
 public       | mdl_question | generalfeedback       | text
 public       | mdl_question | generalfeedbackformat | smallint
 public       | mdl_question | defaultmark           | numeric
 public       | mdl_question | penalty               | numeric
 public       | mdl_question | qtype                 | character varying
 public       | mdl_question | length                | bigint
 public       | mdl_question | stamp                 | character varying
 public       | mdl_question | timecreated           | bigint
 public       | mdl_question | timemodified          | bigint
 public       | mdl_question | createdby             | bigint
 public       | mdl_question | modifiedby            | bigint
(16 rows)

**Comment by trampgeek** [comment]
It seems you are running Moodle 4.0 but are using the version of CodeRunner for Moodle 3.x. There's a stable Release Candidate of CodeRunner (CodeRunner V5.0) for Moodle 4.0 at https://moodle.org/plugins/qtype_coderunner/versions. Or on GitHub: https://moodle.org/plugins/qtype_coderunner/versions

**Comment by dluschan** [comment]
I am not available to update this plugin, nor to delete it. Please tell me how to update it correctly in manual mode.
