### ISSUE TITLE
Plugin does not work on the moodle 4.1

### ISSUE THREAD

**Issue by ibecir** [trampgeek/moodle-qtype_coderunner#156]
The moodle plugin is not working on moodle 4.1 version. When the support for moodle 4.1 will be released? Thank you in advance

**Comment by timhunt** [comment]
Are you using the latest version? I would expect it work, becuase it works with Moodle 4.0, and there are not chagnes between 4.0 and 4.1 that are likely to break it.

If something is not working, we need a far more accurate report than "is not working" to make any progress here.
