### ISSUE TITLE
Multilanguage questions require to choose a language if user tries to skip it

### ISSUE THREAD

**Issue by XiRouz** [trampgeek/moodle-qtype_coderunner#176]
If a user tries to move on from a page with multi language CodeRunner question via buttons "previous page", "next page", or quiz navigation, or "Finish attempt" button, the coding language selector alerts that you need to choose an item first. This is a minor bug, however, it is a bit annoying.
![image](https://github.com/trampgeek/moodle-qtype_coderunner/assets/55024095/cb000b3f-a0df-4f1a-b938-0e4843ca475b)

**Comment by trampgeek** [comment]
Thanks for reporting. We hardly ever use the multilanguage question type so this inconvenience hasn't really troubled us.

I've just pushed an update to the master branch on github (which is currently a Release Candidate for V5.2.1) that changes the logic in the multilanguage question type to disallow keypresses within the question answer area until a language has been selected. But you can now painlessly use the Next and Previous buttons (which are actually Moodle "submit"s) if you simply wish to step over such questions. 

I think this is actually a more logical approach than postponing the requirement for a language until submission time, as the Ace editor needs the language to do the correct syntax colouring.
