### ISSUE TITLE
Warning: Undefined property behat_prefix

### ISSUE THREAD

**Issue by mazitov-az** [trampgeek/moodle-qtype_coderunner#207]
Hi!
### Use:
* Moodle 4.1
* PHP: 8.0
* qtype_coderunner: 
   * version 2024031500
   * release 5.3.1

I got this error:
`Warning: Undefined property: stdClass::$behat_prefix in moodle/question/type/coderunner/classes/sandbox.php on line 39`
[Link](https://github.com/trampgeek/moodle-qtype_coderunner/blob/master/classes/sandbox.php#L39)

Since there is no such parameter by default "behat_prefix"
I suggest adding a check:
```
if (!empty($CFG->behat_prefix) && $CFG->prefix == $CFG->behat_prefix) {
    require_once($CFG->dirroot .'/question/type/coderunner/tests/fixtures/test-sandbox-config.php');
}
```

I also noticed "behat_prefix" in other places:
[commit](https://github.com/trampgeek/moodle-qtype_coderunner/commit/fb2f72e7a96517b611b2a207f5b7929a17947ae1)

Thank you!

**Comment by trampgeek** [comment]
Thanks for reporting. All occurences should now have been fixed.
