### ISSUE TITLE
Question: Why Gapfiller plugins use globalextra and test0 instead of preload?

### ISSUE THREAD

**Issue by XiRouz** [trampgeek/moodle-qtype_coderunner#224]
Hello, pretty much the title.
Related to both Ace Gapfiller and Gapfiller UI plugins.

We are a little confused on why those UI plugins use "globalextra" or "test0" fields.

1. "globalextra" field is meant to have extra code for all tests in it.
2. "answerpreload" was literally made for entering the source text to be displayed in the editor.
3. Inputting default code in "test0" kind of looks like a hack, since "answerpreload" was meant for this.

I took a quick look through the code of those UI plugins and didn't really see why "answerpreload" is not used as intended.
Is there something I am missing? Maybe "answerpreload" is required for something else in these plugins?..

**Comment by trampgeek** [comment]
Excellent question. But it really belongs in one of the two forums on coderunner.org.nz. So I've answered it there: https://coderunner.org.nz/mod/forum/discuss.php?d=711

Please post further such questions there.
