### ISSUE TITLE
Answer Box preload support for each language in BUILT_IN_PROTOTYPE_multilanguage questions.

### ISSUE THREAD

**Issue by majidabdulred** [trampgeek/moodle-qtype_coderunner#225]
I want a Answer Box preload support for multilang questions.

I want to organise coding competitions using this plugin.  This does support multi language using the 
/. But the only problem is it doesnt support answer box preload for those languages.
There is just one "Answer box preload" and i can input prefilled code for just one language there.

Is there any other workaround ? If not, can you please add this feature.

**Comment by trampgeek** [comment]
I've answered this question in the Question author's forum on coderunner.org.nz, here: https://coderunner.org.nz/mod/forum/discuss.php?d=712
