### ISSUE TITLE
We need more descriptive messages for custom grader errors

### ISSUE THREAD

**Issue by kcleung** [trampgeek/moodle-qtype_coderunner#34]
I am using a template grader.  When the sandbox times out, Coderunner spits out this very non-descriptive error message:

Bad output from grader: (nothing). Please report this error to your tutor.

from this line in qtype_coderunner.php:
$string['brokencombinatorgrader'] = 'Bad output from grader: {$a->output}. Please report this error to your tutor.';

Is it possible to give a more meaningful message that can distinguish from other errors such as out of memory?

**Comment by trampgeek** [comment]
The assumption with template graders is that the question author catches and reports on all the things that the student might do wrong - not only bad output but exceptions, such as segmentation faults. I'm inclined to put time limit exceeded in the same category as run time exceptions. This means that when running the student's code from within your template grader, you should put a time limit on it. If you're using a Python template grader, you'd usually run the student code in a subprocess and I'd recommend that you set a timeout on that subprocess, which must be less than the overall timeout set in the question type. The subprocess will then throw an exception, which the template grader can then report on.

However, handling memory limit or process limit errors within the student code is more problematic and I agree that the error message should be altered to at least acknowledge that possibility. 

Richard
