### ISSUE TITLE
Feature Request: Command Line Arguments

### ISSUE THREAD

**Issue by austinholler** [trampgeek/moodle-qtype_coderunner#36]
Hello,

I'm a Data Structures instructor, currently using CodeRunner for running student C++ code. Recently in an attempt to utilize CLAs (e.g. `./someProgram foo.txt 12`) with the cpp_program option, I was unable to find support for this feature.

Is this something that there would be an interest in? Or is there a reason it hasn't been implemented before?

I would say, if there is such an interest, we actually have a guy here on campus who's quite familiar with the CodeRunner codebase and is also interested in helping us implement it. The plan so far would be something simple like adding an additional input box/field to the current setup as a CLA input field. We would just probably need a pointer (no pun intended) to where in the codebase something like this would live.

Thanks!

**Comment by trampgeek** [comment]
Hi Austin

Thanks for the offer to help with the implementation of this. However, I don't think it's actually necessary. I recommend handling all trickier CodeRunner applications by using the template as a script to run whatever commands you like. I usually use a Python template but you can use any of the available languages for scripting.

Here's a simple Python template that compiles and runs a student's C++ program using a shell command line (including arguments) that's provided as the test code. You could of course make this a new question type (see the documentation on making your own question types), if you want to do this sort of thing very often. I attach a screen dump of an example use of this template, namely "Write a C++ program that prints its arguments one per line".

        import subprocess

        __student_answer__ = """{{ STUDENT_ANSWER | e('py')}}"""

        COMPILE = "g++ -Wall -Werror -o program program.cpp".split()

        f = open("program.cpp", "w")
        f.write(__student_answer__)
        f.close()
        try:
            subprocess.check_output(COMPILE, stderr=subprocess.STDOUT, universal_newlines=True)
        except subprocess.CalledProcessError as e:
            print("Error compiling program", file=sys.stderr)
            print(e.output, file=sys.stderr)
        else:
            try:
                cmd = """{{ TEST.testcode | e('py') }}"""
                subprocess.check_call(cmd, stderr=subprocess.STDOUT, shell=True, universal_newlines=True)
            except subprocess.CalledProcessError as e:
                print("Error running program", file=sys.stderr)
                print(e.output, file=sys.stderr)
![selection_215](https://user-images.githubusercontent.com/1101142/27162745-f9007a7a-51d6-11e7-9ce5-f7aa4c4756cc.png)

Let me know if that's not what you're after or if you need help getting it going.

BTW: posting to the question authors forum on coderunner.org.nz is probably the best way to deal with questions of this sort.

Richard

**Comment by jrlamb** [comment]
Hello, I need some help. 
When I use this template, I got the following error, attached

![Capture](https://user-images.githubusercontent.com/10180438/122772376-b0917600-d27d-11eb-9c12-f70f9291efa9.png)

So, I cannot input via the command line.

**Comment by trampgeek** [comment]
It look like you are using a Python language template with the sandbox language set to C. Are you perhaps using the code from [this forum thread](https://coderunner.org.nz/mod/forum/discuss.php?d=85) on coderunner.org.nz? If so you need to have the Ace language set to C and the sandbox language set to Python. See the documentation [here](https://github.com/trampgeek/moodle-qtype_coderunner#supporting-or-implementing-new-languages) for details.
