### ISSUE TITLE
Version 3.2.0

### ISSUE THREAD

**Issue by tijcolem** [trampgeek/moodle-qtype_coderunner#42]
Hello, 

I noticed from the moodle plugin page: https://moodle.org/plugins/pluginversion.php?id=14561
That Version 3.2.0 has been released but I don't see this taged in the repo?  Do you know when this will become available?  Our CS Dept highly values your software and thanks for supporting this.

**Comment by trampgeek** [comment]
Thanks TJC for drawing that to my attention. I had updated the version number in version.php but forgotten to add a new tag. Done now.

Richard

**Comment by tijcolem** [comment]
Thanks for the response and putting in the tag!
