### ISSUE TITLE
"Select a question type to see detailed help." could be localized

### ISSUE THREAD

**Issue by lucaboesch** [trampgeek/moodle-qtype_coderunner#50]
In https://github.com/trampgeek/moodle-qtype_coderunner/blob/master/edit_coderunner_form.php#L535, "Select a question type to see detailed help." could be localized and taken from the language file qtype_coderunner.php.

**Comment by trampgeek** [comment]
Thanks for pointing it out, Luca. Done now. Will be in next release.
