### ISSUE TITLE
reCAPTCHA V1 IS SHUTDOWN at at http://coderunner.org.nz/login/signup.php

### ISSUE THREAD

**Issue by germanvaleroelizondo** [trampgeek/moodle-qtype_coderunner#53]
The site at http://coderunner.org.nz/login/signup.php has a 'reCAPTCHA V1 IS SHUTDOWN' warning and no new accounts can be created.

**Comment by trampgeek** [comment]
Many thanks for pointing that out, Germán. I see it's been down for a month now, and I didn't realise. Appreciated. Fixed now.
