### ISSUE TITLE
Please add more languages for Moodle server at http://coderunner.org.nz/

### ISSUE THREAD

**Issue by germanvaleroelizondo** [trampgeek/moodle-qtype_coderunner#56]
Hi Richard,
Thanks for fixing the reCAPTCHA problem. I have successfully registered and I hope I can now learn a bit more about your plugin.

According to Tim Hunt's post at https://moodle.org/mod/forum/discuss.php?d=241098#p1046621 , "**Language packs have almost 0 impact on Moodle performance**."

So, I think it might be a good idea for you to install some more  languages in your Moodle server at http://coderunner.org.nz/. Many of the strings from this plugin have already been translated into German, Romanian and Mexican Spanish. 

This would allow people like me (a Moodle translator) to check how well the Mexican Spanish translation of your plugin works in a properly configured server that hosts many CodeRunner question types. And it would also allow me to take some screen dumps, in order to illustrate the recently created Moodle Docs in Spanish page for this plugin at https://docs.moodle.org/all/es/Tipo_de_pregunta_CodeRunner :)

I hope you don't mind that I have copied much of your plugin documentation into a Moodle Docs page at https://docs.moodle.org/34/en/CodeRunner_question_type . This page can now be easily translated into languages other than English, and help many more Moodlers world-wide. This Moodle Docs page is also linked when a teacher presses the 'Moodle Docs for this page' at the bottom of a page when the teacher is creating/editing a CodeRunner question type. Please feel free to add/remove/change as much as you think is needed.

I have now completed 100% translation in AMOS of your CodeRunner plugin and I hope to have a Mexican Spanish language pack with 100% translated strings for all core and 'Early Bird 3.5' plugins by the time of the 3.5 Official release date :)

**Comment by trampgeek** [comment]
Hi German

My sincere apologies - I somehow missed this posting altogether, and only just noticed it after fixing the privacy API issue, which you drew my attention to.

Many thanks for all your work on translating the plugin documentation in AMOS - I'm honoured that you chose to translate the CodeRunner plugin :-)

I've added German, Mexican Spanish, International Spanish and Romanian language packs to coderunner.org.nz. Checking the Spanish appearance I immediately noticed one case where I'd failed to use a language string - the 'Result' column header in the result table. I've fixed that in my code and it will go out in the next push. But there are probably others - please let me know of any you notice.

Thanks for your great work for the community.

Richard
