### ISSUE TITLE
Too many params passed to js_call_amd

### ISSUE THREAD

**Issue by cdaly2** [trampgeek/moodle-qtype_coderunner#59]
I have coderunner 2018042800 on ubuntu server 18.04 with moodle version 2018071300.00.
The supporting plugin is adaptive_adapted_for_coderunner version 2018042800.

I have no other plugins installed.

I have all developer debug messages sent to the screen and when I create a coderunner question, I get the following message:

line 1026 of /lib/outputrequirementslib.php: call to debugging()
line 77 of /question/type/coderunner/edit_coderunner_form.php: call to page_requirements_manager->js_call_amd()
line 204 of /lib/formslib.php: call to qtype_coderunner_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 217 of /question/type/questiontypebase.php: call to question_edit_form->__construct()
line 201 of /question/question.php: call to question_type->create_editing_form()

Then, when I save the question type, I get the following error:

Too many params passed to js_call_amd("qtype_coderunner/authorform", "initEditForm")
line 1026 of /lib/outputrequirementslib.php: call to debugging()
line 77 of /question/type/coderunner/edit_coderunner_form.php: call to page_requirements_manager->js_call_amd()
line 204 of /lib/formslib.php: call to qtype_coderunner_edit_form->definition()
line 113 of /question/type/edit_question_form.php: call to moodleform->__construct()
line 217 of /question/type/questiontypebase.php: call to question_edit_form->__construct()
line 201 of /question/question.php: call to question_type->create_editing_form()

I am using a development version of Moodle, but I got a similar message with a current version of Moodle 3.5.

Thanks.

**Comment by trampgeek** [comment]
I posted a [report to the Moodle Bug Tracker](https://tracker.moodle.org/browse/MDL-61990) in April about that particular call to debugging in the Moodle core. I was hoping it might be treated as a bug and fixed, but it has been deemed not a bug. So I've refactored my code to avoid the issue. The updated code is in the development branch and will be pushed to the master within a week or so.

**Comment by timhunt** [comment]
Richard, you say "The updated code is in the development branch and will be pushed to the master within a week or so." but I don's see any sign of the required chagnes in any branch. Am I being dense?

We have just hit this, and I am about to push a fix.

**Comment by timhunt** [comment]
Those changes are needed if you have an 'Answer box preload' of about 1 Kb or more in length. I hope that is helpful.

**Comment by trampgeek** [comment]
Thanks Tim. Been away all day, just got home late. No time to inspect your code, but I'm sure it will be good. Will look tomorrow. FYI, the problem used to occur regardless of the answer box preload because I was passing all the language strings in a single parameter array. That was the fix I was referring to. I hadn't encountered the issue with the answer box preload as I rarely use it. Thanks for fixing.

**Comment by trampgeek** [comment]
That's a great fix, thanks Tim. I didn't know you could plug in data attributes like that. I thought I had to use Ajax for all the stuff I couldn't pass as parameters, which was a a big hassle. This is so much better. Thanks for fixing the unhelpful debugging message, too, where you point out the possibility of passing info in through attributes.

Are you going to do a pull request or shall I just patch in your changes to my master?

Richard

**Comment by timhunt** [comment]
I just made pull #67 . Sorry I forgot to do that before.
