### ISSUE TITLE
Comments to line code

### ISSUE THREAD

**Issue by sadalsuud** [trampgeek/moodle-qtype_coderunner#63]
Hello, I have a question: can I make comments in coderunner in any specific line of the student's code? As if I were commenting on a document from Microsoft Word or Google Docs? I have been reading the documentation I think it does not currently support it, but can someone please tell me how I could get this feature? Thank you

**Comment by trampgeek** [comment]
No, there's no such feature in CodeRunner nor, as far as I know, in any other Moodle assessment module. You can of course comment on the answer as a whole, but you cannot annotate the answer line-by-line.

It would be very difficult to implement such a feature within the CodeRunner plug-in itself. Also, it is somewhat outside the normal use-case of CodeRunner, which is automated marking.

It would be possible to write your own question type where the student answer isn't the actual code but is instead a link to the code in some repository that permits such annotation. The question type could then pull in the document and grade it, and you could then yourself annotate the document afterwards. In [this thread on the CodeRunner question authors' forum](http://coderunner.org.nz/mod/forum/discuss.php?d=52), Trent Lewis describes a question type he has developed in which students submit an SVN revision number and the question type checks out the question and grades it. If the repository allowed you to annotate the submitted code, this would perhaps give you what you want. But developing such a question type requires a fairly deep understanding of CodeRunner.

Please post any further questions on this topic or similar on the [CodeRunner question authors' forum](http://coderunner.org.nz/mod/forum/view.php?id=51).

Richard
