### ISSUE TITLE
PHP question type: Error in question check

### ISSUE THREAD

**Issue by adpe** [trampgeek/moodle-qtype_coderunner#64]
Hello @trampgeek 

I encountered the same error as discussed in this topic http://coderunner.org.nz/mod/forum/discuss.php?d=5

Now your entry fixes the issue, but when do you fix this plugin?
![image](https://user-images.githubusercontent.com/9467708/47090930-2c60d800-d224-11e8-8e1c-7b9f6e9b3a72.png)

I just want to bring it up, maybe it got forgotten.

Greets
Adrian

**Comment by trampgeek** [comment]
Indeed that one seems to have fallen through the cracks. I've fixed it now, and added a test case to make sure it stays fixed. I just pushed the fix to github.

Thanks for reporting it. I don't use that question type myself, so I depend on users reporting issues.
