### ISSUE TITLE
DB error in question_get_top_category: found more than one record!

### ISSUE THREAD

**Issue by adpe** [trampgeek/moodle-qtype_coderunner#65]
Hello @trampgeek 

I've found another bug/issue. After installing the CodeRunner qtype it add's following row to the `<prefix>_question_categories` table:
```
id: 226943
name: CR_PROTOTYPES
contextid: 1
info: Category for CodeRunner question built-in prototypes. FOR SYSTEM USE ONLY.
infoformat: 0
stamp:
parent: 0
sortorder: 999
```

The problem here is, that the contextid should not be 1? Only the top and default system category have this context defined. For what is this `CR_PROTOTYPES`?

Debugging message:
```
Error: mdb->get_record() found more than one record!
line 1583 of /lib/dml/moodle_database.php: call to debugging()
line 1543 of /lib/dml/moodle_database.php: call to moodle_database-&gt;get_record_sql()
line 1522 of /lib/dml/moodle_database.php: call to moodle_database-&gt;get_record_select()
line 1263 of /lib/questionlib.php: call to moodle_database->get_record()
line 1317 of /lib/questionlib.php: call to question_get_top_category()
line 487 of /question/editlib.php: call to question_make_default_categories()
line 328 of /question/editlib.php: call to question_build_edit_resources()
line 31 of /question/edit.php: call to question_edit_setup()
```

Thanks for your help
Adrian

**Comment by trampgeek** [comment]
Can you clarify when and how this error occurs, please? Are you perhaps trying to manually import the builtin_PROTOTYPES.xml file? That's a system file that should only be used by the system during installation or upgrade.

The CR_PROTOTYPES category is indeed a top level system category in which all the CodeRunner prototype questions reside.

To upgrade CodeRunner from a previous version, you should do a git pull. Then, log in to Moodle as an administrator go to notifications and accept the upgrade-plugin suggestion. CodeRunner will delete all the existing questions in the CR_PROTOTYPES category and import the new current versions from the file db/builtin_PROTOTYPES.xml .

**Comment by adpe** [comment]
Thanks for your reply.

I've just pulled the changes and done an upgrade of the plugin. The debugging message is still there. It's shown up in the question bank overview. Please notice, that full debug is on, it's a development server.

```
[<user>@<hostname> coderunner]# git pull
Updating caa05e4..b131d67
Fast-forward
 Readme.md                    |  2 +-
 changehistory.md             |  3 +-
 db/builtin_PROTOTYPES.xml    |  4 +--
 lang/en/qtype_coderunner.php |  5 ++-
 tests/helper.php             | 27 ++++++++++++++-
 tests/phpquestions_test.php  | 78 ++++++++++++++++++++++++++++++++++++++++++++
 version.php                  |  2 +-
 7 files changed, 112 insertions(+), 9 deletions(-)
 create mode 100644 tests/phpquestions_test.php
[<user>@<hostname> coderunner]#
```

**Comment by sleitao** [comment]
Same problem here. The error shows when accessing to any question bank page on any course.
Just installed the module on moodle 3.5. A category named CR_PROTOTYPES with `parent=0` and `contextid=1` (site level) shows up on `<prefix>_question_categories` table.
On `lib/questionlib.php` line 1263
`$category = $DB->get_record('question_categories', array('contextid' => $contextid, 'parent' => 0));`
returns 2 records and only one should be returned.
If it is a top category the contextid should be related to the course, not the site.

**Comment by trampgeek** [comment]
I'm not sure what has happened here. Is the debugging message that you're now getting _exactly_ the same as before? If so it seems you've somehow got two "Top" question categories in some context but I don't know how that comes about. It's not something I've ever seen before.

You said "After installing the CodeRunner qtype it add's following row to the <prefix>_question_categories table". But the record you were identifying was just the CR_PROTOTYPES category which is always added by CodeRunner when it is first installed. That doesn't/shouldn't cause any issues.

Can you remember what you were doing at the time the issue arose? From previous correspondence you had already installed CodeRunner in the past. It seems from your most recent posting that you hadn't upgraded by the usual git pull, so ... how had you gone about upgrading from the earlier version without doing that? Please give as much history as possible.

Do you know in which context you have two instances of the "top" category?

Richard

**Comment by sleitao** [comment]
I have installed version 2018080300 some time ago. I have just intalled it on a moodle test server and haven't done anything else with it. Yesterday I was testing some other things on moodle and I noticed this error. Thought it was something related with my testing, but then I found the same error here:

```
Error: mdb->get_record() found more than one record!

    line 1583 of /lib/dml/moodle_database.php: call to debugging()
    line 1543 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
    line 1522 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
    line 1264 of /lib/questionlib.php: call to moodle_database->get_record()
    line 1318 of /lib/questionlib.php: call to question_get_top_category()
    line 487 of /question/editlib.php: call to question_make_default_categories()
    line 328 of /question/editlib.php: call to question_build_edit_resources()
    line 31 of /question/edit.php: call to question_edit_setup()
```

**Comment by trampgeek** [comment]
OK, I just fired up a new Ubuntu 18.04 on Digital Ocean, installed the very latest Moodle and the very latest CodeRunner, pulled directly from github. All went OK. Full debugging is turned on. And I have a couple of other test servers running Moodle 3.5 + various recent versions of CodeRunner. So I'm now baffled. 

sleitao: can you confirm that you haven't touched CodeRunner since you installed version 2018080300. Did you install it from the Moodle repository or via github? And can you clarify under what situations you see the error, please? Perhaps include a screen dump?

But right now it's bed time in New Zealand :)

Richard

**Comment by trampgeek** [comment]
Thanks sleitao. That helps a lot.

I now understand what has happened and can replicate it. The Moodle code for handling  question categories has changed significantly in Moodle 3.5. In Moodle 3.4 when you created new categories in the system context via the web interface they had contextid=1 and parent=0. That is what the CodeRunner installer does, too - CR_PROTOTYPES is a system level category and is set up with parent=0. In Moodle 3.5, however, it seems that the case of parent=0 for any particular context is reserved for the so-called "top category" for that context. Hence the errors.

In my testing with Moodle 3.5 I always installed CodeRunner immediately on a freshly installed Moodle. It seems that CR_PROTOTYPES category then plays the role of "Top category" in the system context. It's no longer visible as an explicit category in the question bank, but nor do you get any errors.

I'd like to check with Tim Hunt on the best way to handle this problem in the installer and updater. I'll post when I have a full solution. In the meantime, I think you'll be able to fix the problem on your current systems with the following sql query, which sets the parent of the CR_PROTOTYPES category to the system 'top' category. Of course, all the usual "use-at-your-own-risk" and "backup your database first" caveats apply.

    update mdl_question_categories
    set parent=(
        select cats.id from (select * from mdl_question_categories) as cats
        where cats.name='top' and contextid=1)
    where name='CR_PROTOTYPES' and contextid=1;

If you'd be more comfortable with a 2-step manual approach you can first run the query

    select id, name, contextid, parent from mdl_question_categories where contextid=1;

The output should be something like 

    +----+--------------------+-----------+--------+
    | id | name               | contextid | parent |
    +----+--------------------+-----------+--------+
    |  5 | top                |         1 |      0 |
    |  6 | Default for System |         1 |      5 |
    |  7 | CR_PROTOTYPES      |         1 |      0 |
    +----+--------------------+-----------+--------+

You need to set the parent of the CR_PROTOTYPES question to be the id of the top question, so you'd then run the query

    update mdl_question_categories
    set parent=<id of top category>
    where name='CR_PROTOTYPES' and contextid=1;
    
where `<id of top category>` is the appropriate id from the first query (5 in the example).

Thanks Adrian and Sleitao for reporting.

Richard

**Comment by adpe** [comment]
Thanks it does the trick! 

Now I've as well the 19 pre-build prototype questions in this category, before they were not visible.

**Comment by trampgeek** [comment]
Thanks Adrian.

I've changed the installer/updater to handle the new top categories in Moodle 3.5 and pushed it to github as v3.5.3. It should also patch any systems like yours that were damaged by installing the previous version.

Hopefully all fixed now.

Thanks for reporting.

Richard

**Comment by adpe** [comment]
Hi @trampgeek 

I just installed the newest release in a clean Moodle 3.5.2+ (Build: 20181023) instance and it works.

**Comment by trampgeek** [comment]
Thanks Adrian.
