### ISSUE TITLE
Twig expansion in General Feedback

### ISSUE THREAD

**Issue by samfearn** [trampgeek/moodle-qtype_coderunner#66]
Hi,

I'm writing Python3 questions using Coderunner, and was using a template parameter to hold the name of a function. I have a few similar questions, and so I wanted to be able to just change a function name once in the parameters rather than everywhere. I have the 'Hoist template parameters` and `Twig all` options turned on, and the function name is successfully expanded in the question text, the answer and the tests, but isn't expanded in the general feedback. It just prints {{ fnname }} in the general feedback text. I presume I don't need to be doing any escaping, as it successfully expands everywhere else, so this is presumably just a bug?

Thanks,

Sam

**Comment by trampgeek** [comment]
Hi Sam

Thanks for reporting this. Indeed, it's a simple bug. I never use General Feedback myself.

It's fixed in the development branch on github if you want it urgently, and will be pushed to the master branch on the next version update.

Richard

**Comment by trampgeek** [comment]
Hi Sam

An interesting question. I've posted it and my response to the 
CodeRunner question author's forum, here 
<https://coderunner.org.nz/mod/forum/discuss.php?d=153>. If you have 
further comments/questions/suggestions would you mind posting them there 
too, please? I'd be interested to hear exactly what you're wanting to 
do. I can possibly add extra functionality but I am worried about 
further cluttering the already very cumbersome question authoring user 
interface. I'd want to be convinced there was a worthwhile gain to a 
significant number of users.

Cheers

Richard

**Comment by trampgeek** [comment]
Closing as General Feedback is now Twig-expanded and the issue of feedback has moved to the CodeRunner forum.
