### ISSUE TITLE
Version problem upgrading Moodle from 3.2.x to 3.3.x

### ISSUE THREAD

**Issue by sgparry** [trampgeek/moodle-qtype_coderunner#68]
Code Runner 2018103000 appears to be available for 3.2.x and 3.4.x but only version 2018071000 is available for 3.3.x - This means that the Moodle upgrade disables the plug-in and refuses to 'upgrade' it as it considers it a downgrade.

**Comment by trampgeek** [comment]
That was just a slip up when adding the last version. Should be fixed now. Thanks for reporting.
