### ISSUE TITLE
Fix snip method

### ISSUE THREAD

**Issue by imarichev** [trampgeek/moodle-qtype_coderunner#73]
The snip method of qtype_coderunner_util class in util.php, that cuts the middle of the string, messes up UTF-8 encodings, so moodle throws exception after trying to save attempt data to question_attempt_step_data table.
In my case it happens with big test case data in russian with utf8mb4 encodings on both moodle and mysql sides.
There is a FIXME comment near snip method about this problem, so I can assume, that you are awared of it already. But I don't found any Issues.
I was forced to comment out snip method call in tidy mehod to give users the ability to keep working with this questions, so now it lookes like this:
```
      public static function tidy($s) {
        if ($s === null) {
            return null;
        } else {
            return $cleaneds = self::clean($s);
            //return self::snip($cleaneds);
        }
    }
```
Is there any updates about this problem?

**Comment by trampgeek** [comment]
Thanks for the fix, Ivan. Closing this now.
