### ISSUE TITLE
request documentation for adding new language support

### ISSUE THREAD

**Issue by jimka2001** [trampgeek/moodle-qtype_coderunner#89]
Can you please add documentation of how to add new language support?    If I want to add a new question type which requires students to write code in language XYZ, how can I do it, and what assumptions does code runner make about the language?

When I look at the code architecture [the architecture doc](https://coderunner.org.nz/mod/book/view.php?id=179&chapterid=657) there is something referred to as the "Executable program" which is the output of the Twig template engine.  However, "executable program" is not really defined.   Is this assumed to be a single ascii file?  Or is this allowed to be a directory structure containing arbitrarily many files in arbitrarily many subdirectories?

**Comment by jimka2001** [comment]
In the mean time, I have found [supporting-or-implementing-new-languages](https://github.com/trampgeek/moodle-qtype_coderunner/blob/master/Readme.md#supporting-or-implementing-new-languages).

**Comment by trampgeek** [comment]
That is the recommended way to add new languages. It requires minimal sys admin support - they just need to add the new language to the Jobe server - and is far more flexible and maintainable than modifying the source code. The question author has complete control over compile and run time options and can easily add extra pre-and post-filtering. Virtually all our question types nowadays are scripted in Python.

**Comment by jimka2001** [comment]
Can you explain how the model works if I'm using some language with this model and I want to have the student submit one piece of code, but have several tests run?   For example I have one unix command line which compiles the code and runs all the tests.

**Comment by trampgeek** [comment]
Can you ask this question on the CodeRunner question authors forum, please? I'll answer it there so it's more accessible to others.

**Comment by jimka2001** [comment]
done
