### ISSUE TITLE
Java alternate main method not recognised

### ISSUE THREAD

**Issue by adrijanrogan** [trampgeek/moodle-qtype_coderunner#91]
In Java, the main method is defined (per Java language specification [document](https://docs.oracle.com/javase/specs/jls/se8/html/jls-12.html#jls-12.1.4)) as:

    `public static void main(String[] args)` 

However, Java does not care about the order of the `public` and `static` modifiers. The following code is also valid:

    `static public void main(String[] args)`

This is confirmed in the [specification](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-MethodModifier) - the relevant bit is `If two or more (distinct) method modifiers appear in a method declaration, it is customary, though *not required*, that they appear in the order consistent with that shown above in the production for MethodModifier.` (emphasis mine).

The javac compiler compiles both the first and the second variant. CodeRunner however can run the first, but not the second. Instead, a syntax error is reported (at least when using java_program type):
`prog.java:1: error: class X is public, should be declared in a file named X.java`, where X is any valid class name.

~I believe this is due to the "hardcoded" main method [here](https://github.com/trampgeek/moodle-qtype_coderunner/blob/7f81189f02e4d4cb1f7176b71b7654932f7ba9b9/ace/snippets/java.js#L175).~

EDIT: on further inspection, the source of this problem is [this](https://github.com/trampgeek/moodle-qtype_coderunner/blob/0ec292a61e2536d6068bcda25fa29926787b3a6b/classes/jobesandbox.php#L229) function.

**Comment by trampgeek** [comment]
Yes, you've identified the source of the problem. There is some discussion on this in a CodeRunner forum thread, [here](https://coderunner.org.nz/mod/forum/discuss.php?d=135).

I don't teach Java myself but my feeling is that it shouldn't be a major problem in practice - surely students learn very quickly to order their modifiers in the expected way if they wish their code to pass the tests? However, I'll make a note to consider it for the next upgrade. Perhaps you could provide me with a better regular expression? Although as noted in the code unless you do a full parse of the file (which doesn't appeal to me - Java is quite slow enough as it is) there will always be fail cases.

BTW - I think the CodeRunner forum would be a better place to post reports like this. But thanks for reporting.

**Comment by adrijanrogan** [comment]
Thanks, I haven't noticed the forum and have not found a contributing guide here on GitHub by a quick glance.

I agree that this is usually not a problem and that the order in the existing regular expression is de-facto. However, the error message is quite unhelpful and it is valid Java code after all (it happened to at least one of the students on our assignment). I have local changes ready with added test cases (`javaquestions_test.php` and `jobesandbox_test.php`, not sure if both are needed), but the regular expression change is only this (added an or with reverse order):

`$pattern = '/(^|\W)public\s+class\s+(\w+)[^{]*\{.*?(public\s+static|static\s+public)\s+void\s+main\s*\(\s*String/ms';`

**Comment by trampgeek** [comment]
Thanks Adrian. I've updated my copy of CodeRunner so the fix will go out in the next push. The Jobe server has the same pattern so I've updated that too.
