### ISSUE TITLE
GDPR compliance?

### ISSUE THREAD

**Issue by paintdog** [trampgeek/moodle-qtype_coderunner#93]
Can you add a section to the readme to what extent your extension complies with the GDPR? Is there anything to consider?

**Comment by timhunt** [comment]
This does not require info in the Readme. All well maintained Moodle plugins (and CodeRunner is one) integrate with Moodle's Privacy subsystem. This provides all the metadata and other things you need related to GDPR, right in the Moodle admin screens. https://docs.moodle.org/en/View_plugin_privacy_registry
