### ISSUE TITLE
question types

### ISSUE THREAD

**Issue by yakarsu** [trampgeek/moodle-qtype_coderunner#94]
Hello

I need python3_cosc121 this type how can i upload in coderunner

**Comment by trampgeek** [comment]
It's one of the question prototypes in this file: https://github.com/trampgeek/moodle-qtype_coderunner/blob/master/samples/uocprototypes.xml

**Comment by yakarsu** [comment]
Thank you i can put on coderunner file on the server?

**Comment by trampgeek** [comment]
Sure. It's a Moodle XML question export. Just download it from github then import it into Moodle using the question bank import functionality.

**Comment by yakarsu** [comment]
thank you for answer trampgeek
