### ISSUE TITLE
Placeholders using in SQL queries

### ISSUE THREAD

**Issue by otatarintseva** [trampgeek/moodle-qtype_coderunner#97]
Hello,

First of all I want say thank you for your work with the plugin.

We found some code fragments which should be changed to comply Moodle code requirements: 
https://docs.moodle.org/dev/Data_manipulation_API#Placeholders
* in question/type/coderunner/classes/bulk_tester.php in category_path() method the variable $catid is concatenated directly to SQL query. It should be passed as one of the parameters to $DB->get_record_sql() instead. 

Best regards,
Olena Tatarintseva

**Comment by trampgeek** [comment]
Thanks for the heads up. Fixed on my development system and will appear in the next push.
