### ISSUE TITLE
 ISSUE MAY BE DELETED

### ISSUE THREAD

**Issue by cooltopics** [trampgeek/moodle-qtype_coderunner#99]
### **SOLUTION IN DOCUMENTATION ONLY: ISSUE MAY BE DELETED**

```
Error in question

Exception: Bad JSON output from combinator grader output. Output was: {"comment":"All good!"}

```
In the above I am just disp'ing the following:  {"comment":"All good!"}
What is the expected format for the grader output?
In octave how will it be achieved?

I don't find any documentation nor any pointer to where the default templates are stored in the code.
Thanks.

Maybe, a little documentation can help a much.

**Comment by trampgeek** [comment]
From the change in title I assume you've found the documentation (both through the inline help and at coderunner.org.nz), so I'll close this issue.

**Comment by cooltopics** [comment]
After going through the source code, I would like to inform that the issue is actually there:

The following in documentation:
https://github.com/trampgeek/moodle-qtype_coderunner#per-test-case-template-grading

does not matches with the source code:
https://github.com/trampgeek/moodle-qtype_coderunner/blob/6ea8d8917af08189603f23c50725bb0a3af67255/classes/combinator_grader_outcome.php#L32

**Comment by cooltopics** [comment]
After going through the source code, I would like to inform that the issue is actually there:

The following in documentation:
https://github.com/trampgeek/moodle-qtype_coderunner#per-test-case-template-grading

does not matches with the source code:
https://github.com/trampgeek/moodle-qtype_coderunner/blob/6ea8d8917af08189603f23c50725bb0a3af67255/classes/combinator_grader_outcome.php#L33

**Comment by cooltopics** [comment]
After going through the source code, I would like to inform that the issue is actually there:

The following in documentation:
https://github.com/trampgeek/moodle-qtype_coderunner#per-test-case-template-grading

does not match with the source code:
https://github.com/trampgeek/moodle-qtype_coderunner/blob/6ea8d8917af08189603f23c50725bb0a3af67255/classes/combinator_grader_outcome.php#L33

**Comment by trampgeek** [comment]
Hi cooltopics

Thanks for the update. However, I'm not sure what you're seeing as a 
problem. The documentation link is to /Per-test-case template grading/, 
which applies when you have selected a template grader but haven't also 
clicked /Is Combinator/. The JSON output from the template grader in 
this case specifies just one row of the results table.

The source code link is to the $allowedfields attribute of the class 
qtype_coderunner_combinator_grader_outcome, which lists the attributes 
allowed with combinator template graders. These are more sophisticated 
graders that control the entire feedback from the question, over all 
test cases.

Richard
